# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvnetDescription',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('avnet_description_id', models.IntegerField()),
                ('avnet_name', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('descrtiption', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('abstract', models.TextField(null=True)),
                ('prerequisits', models.TextField(null=True)),
                ('topic', models.TextField(null=True)),
                ('last_modified', models.CharField(max_length=50, null=True)),
                ('created', models.CharField(max_length=50, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AvnetTypeInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('avnet_type_id', models.IntegerField()),
                ('avnet_name', models.CharField(max_length=50, null=True)),
                ('avnet_title', models.TextField(null=True)),
                ('last_modified_str', models.CharField(max_length=25, null=True)),
                ('created_str', models.CharField(max_length=25, null=True)),
                ('last_modified', models.TimeField(null=True)),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('created', models.TimeField(null=True)),
                ('classroom_delivery_method', models.CharField(max_length=200, null=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClassPlSummary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('pl_summary_id', models.IntegerField()),
                ('jmw_class_info_id', models.IntegerField(null=True)),
                ('avent_type_info_id', models.IntegerField(null=True)),
                ('jmw_name', models.CharField(max_length=50, null=True)),
                ('avnet_name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('jmw_locaiton_info_id', models.IntegerField(null=True)),
                ('instructor_id', models.IntegerField(null=True)),
                ('instructor_name', models.CharField(max_length=100, null=True)),
                ('facility_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('material_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('lab_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('travel_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('instructor_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('other_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('total_expense', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('class_prce', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('total_attend', models.IntegerField(null=True)),
                ('total_jmw_attend', models.IntegerField(null=True)),
                ('gross_receipts', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('gross_jmw_receipts', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('po', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=50, null=True)),
                ('instructor_rate', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
                ('net_profit', models.DecimalField(null=True, max_digits=6, decimal_places=2)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='JMWClassInfo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('jmw_class_info_id', models.IntegerField()),
                ('jmw_name', models.CharField(max_length=25, unique=True, null=True)),
                ('avnet_type_info_id', models.IntegerField(null=True)),
                ('avnet_type_name', models.CharField(max_length=50, null=True)),
                ('start_date_str', models.CharField(max_length=50, null=True)),
                ('end_date_str', models.CharField(max_length=50, null=True)),
                ('last_modified_str', models.CharField(max_length=25, null=True)),
                ('created_str', models.CharField(max_length=25, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.CharField(max_length=100, null=True)),
                ('last_modified', models.CharField(max_length=100, null=True)),
                ('last_modified_by', models.CharField(max_length=100, null=True)),
                ('start_date_local', models.DateField(null=True)),
                ('end_date_local', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('duration_unit', models.CharField(max_length=10, null=True)),
                ('public', models.CharField(max_length=10, null=True)),
                ('class_status', models.CharField(max_length=10, null=True)),
                ('gtr', models.CharField(max_length=10, null=True)),
                ('total_registered', models.IntegerField(null=True)),
                ('total_jmw_registered', models.IntegerField(null=True)),
                ('instructor', models.IntegerField(null=True)),
                ('instructor_name', models.CharField(max_length=100, null=True)),
                ('type_url', models.CharField(max_length=200, null=True)),
                ('title', models.TextField(null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('price', models.IntegerField(null=True)),
                ('owned_by', models.CharField(max_length=100, null=True)),
                ('source_by', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=25, null=True)),
                ('jmw_locaiton_info_id', models.IntegerField(null=True)),
                ('room_info_id', models.IntegerField(null=True)),
                ('subcategory', models.CharField(max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
                ('po', models.CharField(max_length=50, null=True)),
                ('tech', models.CharField(max_length=50, null=True)),
                ('labs', models.CharField(max_length=50, null=True)),
                ('lock_price', models.CharField(max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='avnetdescription',
            name='avnet_type_id',
            field=models.ForeignKey(to='lms.AvnetTypeInfo'),
            preserve_default=True,
        ),
    ]
